# #####################################################################
# Automatically generated by qmake (2.01a) Mon Apr 12 10:12:24 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += id3tag.h \
    duplicatetracks.h \
    trackParser.h \
    trackModel.h
FORMS += duplicatetrack.ui
SOURCES += id3tag.cpp \
    main.cpp \
    trackParser.cpp \
    duplicatetracks.cpp
