######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 14 16:23:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/include/taglib

# Input
HEADERS += duplicatetracks.h id3tag.h trackParser.h
FORMS += duplicatetrack.ui
SOURCES += duplicatetracks.cpp id3tag.cpp main.cpp trackParser.cpp
